#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Local trade analysis tool for TD 9-13 strategy outputs.

This script does NOT depend on PTrade. It reads per-stock trade.csv files
generated by backtest.py and creates PNG analysis charts.

Expected folder layout:

<target_folder>/
├── total_statistics.csv
├── 600519SS/
│   ├── signnal.csv
│   ├── trade.csv
│   └── statistics.csv
└── ...

Usage:
    python3 analyse_tool.py
    python3 analyse_tool.py ../reacher_path/2019-01-01
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence


# =============================================================================
# Config
# =============================================================================

# Target folder path, resolved relative to this script's directory unless absolute.
# You can also override it from CLI: python3 analyse_tool.py <target_folder>
TARGET_FOLDER_PATH = "../reacher_path/2019-01-01"

# Input / output names.
TRADE_CSV_NAME = "trade.csv"
STOCK_TABLE_IMAGE = "trade_analysis_table.png"
COMBINED_WIN_RATE_IMAGE = "trade_analysis_win_rate.png"
COMBINED_PROFIT_LOSS_IMAGE = "trade_analysis_profit_loss_ratio.png"
COMBINED_EXPECTANCY_IMAGE = "trade_analysis_expectancy.png"

# CSV columns produced by backtest.py TradeRecordRecorder.
SECURITY_COL = "security"
SETUP_PERFECT_COL = "setup_is_perfect"
COUNTDOWN_PERFECT_COL = "countdown_is_perfect"
BOUGHT_COL = "bought"
BUY_QUANTITY_COL = "buy_quantity"
BUY_PRICE_COL = "buy_price"
SELL_DATE_COL = "sell_date"
PNL_COL = "pnl"


SCENARIOS = [
    {
        "key": "all",
        "label": "All Completed Trades",
        "require_setup_perfect": False,
        "require_countdown_perfect": False,
    },
    {
        "key": "perfect_setup",
        "label": "Perfect Setup",
        "require_setup_perfect": True,
        "require_countdown_perfect": False,
    },
    {
        "key": "perfect_countdown",
        "label": "Perfect Countdown",
        "require_setup_perfect": False,
        "require_countdown_perfect": True,
    },
    {
        "key": "perfect_both",
        "label": "Perfect Setup + Countdown",
        "require_setup_perfect": True,
        "require_countdown_perfect": True,
    },
]


# =============================================================================
# Loading
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate TD 9-13 trade analysis tables and combined charts."
    )
    parser.add_argument(
        "target_folder",
        nargs="?",
        default=TARGET_FOLDER_PATH,
        help="Target output folder path. Relative paths are resolved beside this script.",
    )
    return parser.parse_args()


def script_dir() -> Path:
    return Path(__file__).resolve().parent


def resolve_target_dir(value: str) -> Path:
    target = Path(value).expanduser()
    if not target.is_absolute():
        target = script_dir() / target
    return target.resolve()


def parse_bool(value: object) -> bool:
    text = str(value or "").strip().lower()
    return text in {"1", "true", "t", "yes", "y"}


def parse_float(value: object) -> Optional[float]:
    text = str(value or "").strip()
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


def load_trade_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def discover_trade_files(target_dir: Path) -> Dict[str, Path]:
    trade_files: Dict[str, Path] = {}
    for child in sorted(target_dir.iterdir()):
        if not child.is_dir():
            continue
        trade_csv = child / TRADE_CSV_NAME
        if trade_csv.exists():
            trade_files[child.name] = trade_csv
    return trade_files


# =============================================================================
# Metrics
# =============================================================================

def is_completed_trade(row: Dict[str, str]) -> bool:
    if not parse_bool(row.get(BOUGHT_COL)):
        return False
    if not str(row.get(SELL_DATE_COL, "")).strip():
        return False
    qty = parse_float(row.get(BUY_QUANTITY_COL))
    price = parse_float(row.get(BUY_PRICE_COL))
    pnl = parse_float(row.get(PNL_COL))
    return qty is not None and qty > 0 and price is not None and price > 0 and pnl is not None


def filter_rows_by_scenario(rows: Iterable[Dict[str, str]], scenario: Dict[str, object]) -> List[Dict[str, str]]:
    result: List[Dict[str, str]] = []
    for row in rows:
        if not is_completed_trade(row):
            continue
        if scenario["require_setup_perfect"] and not parse_bool(row.get(SETUP_PERFECT_COL)):
            continue
        if scenario["require_countdown_perfect"] and not parse_bool(row.get(COUNTDOWN_PERFECT_COL)):
            continue
        result.append(row)
    return result


def average(values: Sequence[float]) -> Optional[float]:
    if not values:
        return None
    return sum(values) / len(values)


def calc_metrics(rows: List[Dict[str, str]]) -> Dict[str, Optional[float]]:
    pnls: List[float] = []
    open_values: List[float] = []

    for row in rows:
        pnl = parse_float(row.get(PNL_COL))
        qty = parse_float(row.get(BUY_QUANTITY_COL))
        price = parse_float(row.get(BUY_PRICE_COL))
        if pnl is None or qty is None or price is None:
            continue
        pnls.append(pnl)
        open_values.append(qty * price)

    trade_count = len(pnls)
    if trade_count == 0:
        return {
            "trade_count": 0.0,
            "win_rate": None,
            "profit_loss_ratio": None,
            "expectancy": None,
        }

    wins = [pnl for pnl in pnls if pnl > 0]
    losses = [-pnl for pnl in pnls if pnl < 0]
    win_rate = len(wins) / trade_count
    avg_profit = average(wins) or 0.0
    avg_loss = average(losses) or 0.0
    avg_open_value = average(open_values) or 0.0

    if avg_loss > 0:
        profit_loss_ratio: Optional[float] = avg_profit / avg_loss
    elif avg_profit > 0:
        profit_loss_ratio = math.inf
    else:
        profit_loss_ratio = None

    if avg_open_value > 0:
        expectancy = (win_rate * avg_profit - (1.0 - win_rate) * avg_loss) / avg_open_value
    else:
        expectancy = None

    return {
        "trade_count": float(trade_count),
        "win_rate": win_rate,
        "profit_loss_ratio": profit_loss_ratio,
        "expectancy": expectancy,
    }


def analyse_stock(rows: List[Dict[str, str]]) -> Dict[str, Dict[str, Optional[float]]]:
    metrics: Dict[str, Dict[str, Optional[float]]] = {}
    for scenario in SCENARIOS:
        scenario_rows = filter_rows_by_scenario(rows, scenario)
        metrics[str(scenario["key"])] = calc_metrics(scenario_rows)
    return metrics


# =============================================================================
# Plot Helpers
# =============================================================================

_PLOT_MODULES = None


def get_plot_modules():
    global _PLOT_MODULES
    if _PLOT_MODULES is None:
        import matplotlib

        matplotlib.use("Agg", force=True)
        import matplotlib.pyplot as plt
        from matplotlib.ticker import PercentFormatter

        _PLOT_MODULES = (plt, PercentFormatter)
    return _PLOT_MODULES


def metric_text(value: Optional[float], as_percent: bool = False) -> str:
    if value is None:
        return "N/A"
    if math.isinf(value):
        return "Inf"
    if as_percent:
        return "{:.2%}".format(value)
    return "{:.3f}".format(value)


def numeric_or_nan(value: Optional[float]) -> float:
    if value is None or math.isinf(value):
        return math.nan
    return float(value)


def save_figure(fig, path: Path) -> None:
    plt, _ = get_plot_modules()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)
    print("Saved: {}".format(path))


def setup_category_axis(ax, stocks: List[str], max_labels: int = 80) -> None:
    if not stocks:
        return
    step = max(1, math.ceil(len(stocks) / max_labels))
    tick_positions = list(range(0, len(stocks), step))
    if tick_positions[-1] != len(stocks) - 1:
        tick_positions.append(len(stocks) - 1)
    ax.set_xticks(tick_positions)
    ax.set_xticklabels([stocks[i] for i in tick_positions], rotation=60, ha="right")
    ax.grid(True, linestyle="--", alpha=0.3)


# =============================================================================
# Stock Table
# =============================================================================

def plot_stock_table(stock: str, metrics: Dict[str, Dict[str, Optional[float]]], output_dir: Path) -> None:
    plt, _ = get_plot_modules()
    rows = []
    row_labels = []
    for scenario in SCENARIOS:
        key = str(scenario["key"])
        m = metrics[key]
        count = int(m.get("trade_count") or 0)
        row_labels.append("{} (n={})".format(scenario["label"], count))
        rows.append([
            metric_text(m.get("win_rate"), as_percent=True),
            metric_text(m.get("profit_loss_ratio")),
            metric_text(m.get("expectancy"), as_percent=True),
        ])

    fig, ax = plt.subplots(figsize=(12, 3.8))
    ax.axis("off")
    table = ax.table(
        cellText=rows,
        rowLabels=row_labels,
        colLabels=["Win Rate", "Profit/Loss", "Expectancy"],
        loc="center",
        cellLoc="center",
        rowLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.0, 1.7)
    ax.set_title("{} Trade Quality Summary".format(stock), pad=18)
    save_figure(fig, output_dir / STOCK_TABLE_IMAGE)


# =============================================================================
# Combined Charts
# =============================================================================

def collect_series(
    all_metrics: Dict[str, Dict[str, Dict[str, Optional[float]]]],
    metric_name: str,
) -> Dict[str, List[float]]:
    series: Dict[str, List[float]] = {}
    stocks = list(all_metrics.keys())
    for scenario in SCENARIOS:
        key = str(scenario["key"])
        values = [
            numeric_or_nan(all_metrics[stock][key].get(metric_name))
            for stock in stocks
        ]
        series[str(scenario["label"])] = values
    return series


def plot_combined_metric(
    all_metrics: Dict[str, Dict[str, Dict[str, Optional[float]]]],
    target_dir: Path,
    metric_name: str,
    title: str,
    y_label: str,
    image_name: str,
    percent_axis: bool = False,
) -> None:
    plt, PercentFormatter = get_plot_modules()
    stocks = list(all_metrics.keys())
    fig_width = max(14, min(48, len(stocks) * 0.22))
    fig, ax = plt.subplots(figsize=(fig_width, 7))
    x_values = list(range(len(stocks)))

    for label, values in collect_series(all_metrics, metric_name).items():
        ax.plot(x_values, values, marker="o", linewidth=1.8, markersize=3.0, label=label)

    ax.set_title(title)
    ax.set_xlabel("Stock")
    ax.set_ylabel(y_label)
    if percent_axis:
        ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    setup_category_axis(ax, stocks)
    ax.legend(loc="best")
    save_figure(fig, target_dir / image_name)


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    args = parse_args()
    target_dir = resolve_target_dir(args.target_folder)
    if not target_dir.exists() or not target_dir.is_dir():
        raise FileNotFoundError("Target folder not found: {}".format(target_dir))

    trade_files = discover_trade_files(target_dir)
    if not trade_files:
        raise FileNotFoundError("No trade.csv files found under: {}".format(target_dir))

    all_metrics: Dict[str, Dict[str, Dict[str, Optional[float]]]] = {}
    for stock, trade_csv in trade_files.items():
        rows = load_trade_csv(trade_csv)
        metrics = analyse_stock(rows)
        all_metrics[stock] = metrics
        plot_stock_table(stock, metrics, trade_csv.parent)

    plot_combined_metric(
        all_metrics,
        target_dir,
        metric_name="win_rate",
        title="Win Rate by Stock and Signal Quality",
        y_label="Win Rate",
        image_name=COMBINED_WIN_RATE_IMAGE,
        percent_axis=True,
    )
    plot_combined_metric(
        all_metrics,
        target_dir,
        metric_name="profit_loss_ratio",
        title="Profit/Loss Ratio by Stock and Signal Quality",
        y_label="Average Profit / Average Loss",
        image_name=COMBINED_PROFIT_LOSS_IMAGE,
    )
    plot_combined_metric(
        all_metrics,
        target_dir,
        metric_name="expectancy",
        title="Expected Return by Stock and Signal Quality",
        y_label="Expected Return per Opening Value",
        image_name=COMBINED_EXPECTANCY_IMAGE,
        percent_axis=True,
    )

    print("Done. Analysed {} stocks.".format(len(all_metrics)))


if __name__ == "__main__":
    main()
