#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Local chart tool for TD 9-13 strategy outputs.

This script does NOT depend on PTrade. It reads CSV files generated by
backtest.py and creates PNG charts in the same output folder.

Expected folder layout:

data_tool/
├── tool.py
└── <TARGET_FOLDER_NAME>/
    ├── total_statistics.csv
    ├── 600519SS/
    │   ├── signnal.csv
    │   ├── trade.csv
    │   └── statistics.csv
    └── ...

Usage:
    python3 tool.py
    python3 tool.py 2023-03-13
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter


# =============================================================================
# Config
# =============================================================================

# Target folder name. The folder must be placed beside this tool.py file.
# You can also override it from CLI: python3 tool.py <folder_name>
TARGET_FOLDER_NAME = "../output/2019-04-26"

# Output image names.
STOCK_OVERVIEW_IMAGE = "statistics_overview.png"
COMBINED_WIN_RATE_IMAGE = "combined_win_rate.png"
COMBINED_RETURN_IMAGE = "combined_profitability.png"
TOTAL_POSITION_METRICS_IMAGE = "total_position_metrics.png"


# CSV columns produced by backtest.py StatisticsRecorder.
DATE_COL = "datetime"
SECURITY_COL = "security"
WIN_RATE_COL = "win_rate"
STRATEGY_RETURN_COL = "strategy_return"
BENCHMARK_RETURN_COL = "benchmark_return"
STRATEGY_ANNUALIZED_COL = "strategy_annualized_return"
BENCHMARK_ANNUALIZED_COL = "benchmark_annualized_return"


# =============================================================================
# CSV Loading
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate charts from TD 9-13 strategy statistics CSV files."
    )
    parser.add_argument(
        "target_folder",
        nargs="?",
        default=TARGET_FOLDER_NAME,
        help="Target folder name placed beside tool.py.",
    )
    return parser.parse_args()


def script_dir() -> Path:
    return Path(__file__).resolve().parent


def parse_datetime(value: str) -> Optional[datetime]:
    value = (value or "").strip()
    if not value:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%Y/%m/%d %H:%M:%S", "%Y/%m/%d"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue
    return None


def parse_float(value: str) -> Optional[float]:
    value = (value or "").strip()
    if value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def load_statistics_csv(path: Path) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    if not path.exists():
        return rows

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for raw in reader:
            dt = parse_datetime(raw.get(DATE_COL, ""))
            if dt is None:
                continue
            row: Dict[str, object] = dict(raw)
            row[DATE_COL] = dt
            for col in (
                WIN_RATE_COL,
                STRATEGY_RETURN_COL,
                BENCHMARK_RETURN_COL,
                STRATEGY_ANNUALIZED_COL,
                BENCHMARK_ANNUALIZED_COL,
            ):
                row[col] = parse_float(raw.get(col, ""))
            rows.append(row)

    rows.sort(key=lambda r: r[DATE_COL])
    return rows


def discover_stock_statistics(target_dir: Path) -> Dict[str, List[Dict[str, object]]]:
    result: Dict[str, List[Dict[str, object]]] = {}
    for child in sorted(target_dir.iterdir()):
        if not child.is_dir():
            continue
        stats_csv = child / "statistics.csv"
        if not stats_csv.exists():
            continue
        rows = load_statistics_csv(stats_csv)
        if rows:
            result[child.name] = rows
    return result


# =============================================================================
# Plot Helpers
# =============================================================================

def column_series(
    rows: List[Dict[str, object]],
    column: str,
) -> Tuple[List[datetime], List[float]]:
    dates: List[datetime] = []
    values: List[float] = []
    for row in rows:
        value = row.get(column)
        if value is None:
            continue
        dates.append(row[DATE_COL])  # type: ignore[arg-type]
        values.append(float(value))
    return dates, values


def setup_date_axis(ax) -> None:
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax.xaxis.get_major_locator()))
    ax.grid(True, linestyle="--", alpha=0.3)


def save_figure(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    print(f"Saved: {path}")


def plot_line(ax, rows: List[Dict[str, object]], column: str, label: str, linewidth: float = 1.8) -> None:
    dates, values = column_series(rows, column)
    if not dates:
        return
    ax.plot(dates, values, label=label, linewidth=linewidth)


# =============================================================================
# Chart 1: Per-stock overview
# =============================================================================

def plot_stock_overview(stock: str, rows: List[Dict[str, object]], stock_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    plot_line(ax, rows, WIN_RATE_COL, "Win Rate")
    plot_line(ax, rows, STRATEGY_RETURN_COL, "Strategy Return")
    plot_line(ax, rows, BENCHMARK_RETURN_COL, "Benchmark Return")
    plot_line(ax, rows, STRATEGY_ANNUALIZED_COL, "Strategy Annualized Return")
    plot_line(ax, rows, BENCHMARK_ANNUALIZED_COL, "Benchmark Annualized Return")

    ax.set_title(f"{stock} Performance Statistics")
    ax.set_xlabel("Date")
    ax.set_ylabel("Rate")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(loc="best")
    setup_date_axis(ax)
    save_figure(fig, stock_dir / STOCK_OVERVIEW_IMAGE)


# =============================================================================
# Chart 2: Combined win rate
# =============================================================================

def plot_combined_win_rate(stock_rows: Dict[str, List[Dict[str, object]]], target_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    for stock, rows in stock_rows.items():
        plot_line(ax, rows, WIN_RATE_COL, stock)

    ax.set_title("Combined Win Rate by Stock")
    ax.set_xlabel("Date")
    ax.set_ylabel("Win Rate")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(loc="best", ncol=2)
    setup_date_axis(ax)
    save_figure(fig, target_dir / COMBINED_WIN_RATE_IMAGE)


# =============================================================================
# Chart 3: Combined profitability with benchmark
# =============================================================================

def load_total_benchmark(target_dir: Path) -> Optional[List[Dict[str, object]]]:
    total_csv = target_dir / "total_statistics.csv"
    rows = load_statistics_csv(total_csv)
    return rows or None


def plot_combined_profitability(
    stock_rows: Dict[str, List[Dict[str, object]]],
    target_dir: Path,
    total_rows: Optional[List[Dict[str, object]]],
) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    for stock, rows in stock_rows.items():
        plot_line(ax, rows, STRATEGY_RETURN_COL, f"{stock} Strategy Return")

    if total_rows:
        plot_line(ax, total_rows, BENCHMARK_RETURN_COL, "Benchmark Return (Total)", linewidth=2.8)
    else:
        # Fallback: plot each stock benchmark if total_statistics.csv is unavailable.
        for stock, rows in stock_rows.items():
            plot_line(ax, rows, BENCHMARK_RETURN_COL, f"{stock} Benchmark Return", linewidth=1.2)

    ax.set_title("Combined Strategy Return with Benchmark")
    ax.set_xlabel("Date")
    ax.set_ylabel("Return")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(loc="best", ncol=2)
    setup_date_axis(ax)
    save_figure(fig, target_dir / COMBINED_RETURN_IMAGE)


# =============================================================================
# Chart 4: Total position metrics
# =============================================================================

def plot_total_position_metrics(target_dir: Path, total_rows: Optional[List[Dict[str, object]]]) -> None:
    if not total_rows:
        print("Skipped total position metrics: total_statistics.csv not found or empty.")
        return

    fig, ax = plt.subplots(figsize=(14, 7))
    plot_line(ax, total_rows, WIN_RATE_COL, "Win Rate")
    plot_line(ax, total_rows, STRATEGY_RETURN_COL, "Strategy Return")
    plot_line(ax, total_rows, BENCHMARK_RETURN_COL, "Benchmark Return")
    plot_line(ax, total_rows, STRATEGY_ANNUALIZED_COL, "Strategy Annualized Return")
    plot_line(ax, total_rows, BENCHMARK_ANNUALIZED_COL, "Benchmark Annualized Return")

    ax.set_title("Total Portfolio Metrics Over Time")
    ax.set_xlabel("Date")
    ax.set_ylabel("Rate")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.legend(loc="best")
    setup_date_axis(ax)
    save_figure(fig, target_dir / TOTAL_POSITION_METRICS_IMAGE)


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    args = parse_args()
    target_dir = script_dir() / args.target_folder
    if not target_dir.exists() or not target_dir.is_dir():
        raise FileNotFoundError(f"Target folder not found: {target_dir}")

    stock_rows = discover_stock_statistics(target_dir)
    if not stock_rows:
        raise FileNotFoundError(
            f"No stock statistics.csv files found under: {target_dir}"
        )

    for stock, rows in stock_rows.items():
        plot_stock_overview(stock, rows, target_dir / stock)

    total_rows = load_total_benchmark(target_dir)
    plot_combined_win_rate(stock_rows, target_dir)
    plot_combined_profitability(stock_rows, target_dir, total_rows)
    plot_total_position_metrics(target_dir, total_rows)

    print("Done.")


if __name__ == "__main__":
    main()
