#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Offline thesis analysis tool for TD 9-13 strategy outputs.

This script does not depend on PTrade. It reads metadata generated by
strategies/my_strategy/backtest.py and produces paper-ready CSV tables and PNG
figures under <run_folder>/thesis_analysis/.
"""

from __future__ import annotations

import argparse
import csv
import math
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


# =============================================================================
# Config
# =============================================================================

TARGET_RUN_FOLDER = "../research_path/2016-01-01"
OUTPUT_FOLDER_NAME = "thesis_analysis"

INITIAL_CAPITAL = 10_000_000.0
TRADING_DAYS_PER_YEAR = 252.0
EVENT_WINDOWS = [5, 20, 60, 120]
BOOTSTRAP_ENABLED = False
SINGLE_STOCK_EVENT_MIN_COUNT = 120
SINGLE_STOCK_TRADE_MIN_COUNT = 10


# =============================================================================
# Basic Helpers
# =============================================================================

def script_dir() -> Path:
    return Path(__file__).resolve().parent


def resolve_path(value: str) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = script_dir() / path
    return path.resolve()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate TD thesis analysis tables and charts.")
    parser.add_argument("run_folder", nargs="?", default=TARGET_RUN_FOLDER)
    return parser.parse_args()


def parse_datetime(value: object) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%Y/%m/%d %H:%M:%S", "%Y/%m/%d"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue
    return None


def date_key(value: object) -> str:
    dt = parse_datetime(value)
    return dt.strftime("%Y-%m-%d") if dt else str(value or "")[:10]


def parse_float(value: object) -> Optional[float]:
    text = str(value or "").strip()
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


def parse_bool(value: object) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "t", "yes", "y"}


def safe_div(numerator: float, denominator: float) -> Optional[float]:
    if denominator == 0:
        return None
    return numerator / denominator


def mean(values: Sequence[float]) -> Optional[float]:
    return sum(values) / len(values) if values else None


def quantile(values: Sequence[float], q: float) -> Optional[float]:
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    pos = (len(ordered) - 1) * q
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return ordered[lo]
    return ordered[lo] * (hi - pos) + ordered[hi] * (pos - lo)


def fmt(value: Optional[float], digits: int = 6) -> str:
    if value is None:
        return ""
    if math.isinf(value):
        return "inf"
    return str(round(value, digits))


def iter_progress(iterable, desc: str = "", total: Optional[int] = None):
    try:
        from tqdm import tqdm  # type: ignore
        return tqdm(iterable, desc=desc, total=total)
    except Exception:
        if desc:
            print("{}...".format(desc))
        return iterable


def make_event_id(row: Dict[str, str]) -> str:
    existing = str(row.get("event_id", "")).strip()
    if existing:
        return existing
    raw = "{}|{}|{}|{}|{}|{}".format(
        row.get("security", ""),
        row.get("datetime", ""),
        row.get("type", ""),
        row.get("direction", ""),
        row.get("setup_last_dt", ""),
        row.get("count", ""),
    )
    return raw.replace(" ", "T").replace(":", "").replace("|", "_").replace(".", "")


# =============================================================================
# CSV I/O
# =============================================================================

def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError("Required input not found: {}".format(path))
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: List[Dict[str, object]], header: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(header))
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in header})
    print("Saved: {}".format(path))


# =============================================================================
# Event Study
# =============================================================================

def event_group(row: Dict[str, str]) -> str:
    typ = row.get("type", "")
    if typ.startswith("BUY_SETUP"):
        return "Buy Setup"
    if typ.startswith("SELL_SETUP"):
        return "Sell Setup"
    if typ.startswith("BUY_COUNTDOWN_COMPLETE"):
        return "Buy Countdown Complete"
    if typ.startswith("SELL_COUNTDOWN_COMPLETE"):
        return "Sell Countdown Complete"
    if "COUNTDOWN_CANCEL" in typ:
        return "Countdown Cancel"
    return typ or "Unknown"


def build_outcome_index(outcomes: List[Dict[str, str]]) -> Dict[Tuple[str, int], Dict[str, str]]:
    index: Dict[Tuple[str, int], Dict[str, str]] = {}
    for row in iter_progress(outcomes, desc="Indexing event outcomes", total=len(outcomes)):
        event_id = str(row.get("event_id", "")).strip()
        window = int(parse_float(row.get("window")) or 0)
        if event_id and window:
            index[(event_id, window)] = row
    return index


def directional_metrics(row: Dict[str, str], outcome_index: Dict[Tuple[str, int], Dict[str, str]], window: int) -> Tuple[Optional[float], Optional[float], Optional[float]]:
    outcome = outcome_index.get((make_event_id(row), window))
    if not outcome:
        return None, None, None
    return (
        parse_float(outcome.get("directional_return")),
        parse_float(outcome.get("mfe")),
        parse_float(outcome.get("mae")),
    )


def summarize_values(values: Sequence[float], prefix: str) -> Dict[str, str]:
    wins = [v for v in values if v > 0]
    return {
        "{}_count".format(prefix): str(len(values)),
        "{}_mean".format(prefix): fmt(mean(values)),
        "{}_median".format(prefix): fmt(quantile(values, 0.5)),
        "{}_q25".format(prefix): fmt(quantile(values, 0.25)),
        "{}_q75".format(prefix): fmt(quantile(values, 0.75)),
        "{}_win_rate".format(prefix): fmt(safe_div(float(len(wins)), float(len(values))) if values else None),
    }


def build_event_study(events: List[Dict[str, str]], outcome_index: Dict[Tuple[str, int], Dict[str, str]]) -> List[Dict[str, object]]:
    grouped: Dict[str, List[Dict[str, str]]] = {}
    for row in events:
        grouped.setdefault(event_group(row), []).append(row)

    output: List[Dict[str, object]] = []
    grouped_items = sorted(grouped.items())
    for group, rows in iter_progress(grouped_items, desc="Building event study", total=len(grouped_items)):
        out: Dict[str, object] = {"event_group": group, "event_count": len(rows)}
        for window in EVENT_WINDOWS:
            returns: List[float] = []
            mfes: List[float] = []
            maes: List[float] = []
            for row in rows:
                ret, mfe, mae = directional_metrics(row, outcome_index, window)
                if ret is not None:
                    returns.append(ret)
                if mfe is not None:
                    mfes.append(mfe)
                if mae is not None:
                    maes.append(mae)
            out.update(summarize_values(returns, "ret_{}d".format(window)))
            out["mfe_{}d_median".format(window)] = fmt(quantile(mfes, 0.5))
            out["mae_{}d_median".format(window)] = fmt(quantile(maes, 0.5))
        output.append(out)
    return output


# =============================================================================
# Trade Performance
# =============================================================================

def completed_trades(trades: Iterable[Dict[str, str]]) -> List[Dict[str, str]]:
    result = []
    for row in trades:
        if not parse_bool(row.get("bought")):
            continue
        if not str(row.get("sell_date", "")).strip():
            continue
        if parse_float(row.get("pnl")) is None:
            continue
        result.append(row)
    return result


def scenario_filter(row: Dict[str, str], scenario: str) -> bool:
    setup = parse_bool(row.get("setup_is_perfect"))
    countdown = parse_bool(row.get("countdown_is_perfect"))
    if scenario == "all":
        return True
    if scenario == "perfect_setup":
        return setup
    if scenario == "perfect_countdown":
        return countdown
    if scenario == "perfect_both":
        return setup and countdown
    return True


def entry_value(row: Dict[str, str]) -> float:
    value = parse_float(row.get("entry_value"))
    if value and value > 0:
        return value
    qty = parse_float(row.get("buy_quantity")) or 0.0
    price = parse_float(row.get("buy_price")) or 0.0
    return qty * price


def max_drawdown_from_pnls(pnls: Sequence[float]) -> float:
    nav = 1.0
    peak = 1.0
    max_dd = 0.0
    for pnl in pnls:
        nav += pnl / INITIAL_CAPITAL
        if nav > peak:
            peak = nav
        dd = (peak - nav) / peak if peak > 0 else 0.0
        max_dd = max(max_dd, dd)
    return max_dd


def sharpe_from_returns(values: Sequence[float]) -> Optional[float]:
    if len(values) < 2:
        return None
    avg = mean(values) or 0.0
    variance = sum((v - avg) * (v - avg) for v in values) / (len(values) - 1)
    std = variance ** 0.5
    if std == 0:
        return None
    return avg / std * (TRADING_DAYS_PER_YEAR ** 0.5)


def summarize_trades(trades: List[Dict[str, str]]) -> List[Dict[str, object]]:
    scenarios = [
        ("all", "All Buy Countdown"),
        ("perfect_setup", "Perfect Setup"),
        ("perfect_countdown", "Perfect Countdown"),
        ("perfect_both", "Perfect Setup + Countdown"),
    ]
    rows: List[Dict[str, object]] = []
    base = completed_trades(trades)
    for key, label in scenarios:
        sample = [r for r in base if scenario_filter(r, key)]
        pnls = [parse_float(r.get("pnl")) or 0.0 for r in sample]
        wins = [p for p in pnls if p > 0]
        losses = [-p for p in pnls if p < 0]
        trade_returns = []
        for row, pnl in zip(sample, pnls):
            ev = entry_value(row)
            if ev > 0:
                trade_returns.append(pnl / ev)
        avg_profit = mean(wins) or 0.0
        avg_loss = mean(losses) or 0.0
        total_pnl = sum(pnls)
        total_return = total_pnl / INITIAL_CAPITAL if INITIAL_CAPITAL > 0 else 0.0
        rows.append({
            "scenario": label,
            "trade_count": len(sample),
            "win_rate": fmt(safe_div(float(len(wins)), float(len(sample))) if sample else None),
            "avg_profit_loss_ratio": fmt(safe_div(avg_profit, avg_loss) if avg_loss > 0 else (math.inf if avg_profit > 0 else None)),
            "total_pnl": fmt(total_pnl, 2),
            "total_return": fmt(total_return),
            "max_drawdown": fmt(max_drawdown_from_pnls(pnls)),
            "sharpe": fmt(sharpe_from_returns(trade_returns)),
        })
    return rows


# =============================================================================
# Single-stock Applicability
# =============================================================================

def is_buy_countdown_complete(row: Dict[str, str]) -> bool:
    return row.get("type", "").startswith("BUY_COUNTDOWN_COMPLETE")


def profit_loss_ratio_from_pnls(pnls: Sequence[float]) -> Optional[float]:
    wins = [p for p in pnls if p > 0]
    losses = [-p for p in pnls if p < 0]
    avg_profit = mean(wins) or 0.0
    avg_loss = mean(losses) or 0.0
    if avg_loss > 0:
        return avg_profit / avg_loss
    if avg_profit > 0:
        return math.inf
    return None


def trade_win_rate_from_pnls(pnls: Sequence[float]) -> Optional[float]:
    if not pnls:
        return None
    wins = [p for p in pnls if p > 0]
    return float(len(wins)) / len(pnls)


def split_consistency(
    events: List[Dict[str, str]],
    trades: List[Dict[str, str]],
    outcome_index: Dict[Tuple[str, int], Dict[str, str]],
) -> str:
    if not events:
        return "False"
    ordered_events = sorted(events, key=lambda r: date_key(r.get("datetime", "")))
    mid = len(ordered_events) // 2
    parts = [ordered_events[:mid], ordered_events[mid:]]
    if not parts[0] or not parts[1]:
        return "False"

    event_ok = []
    for part in parts:
        returns = []
        for row in part:
            ret, _, _ = directional_metrics(row, outcome_index, 20)
            if ret is not None:
                returns.append(ret)
        med = quantile(returns, 0.5)
        event_ok.append(med is not None and med > 0)

    ordered_trades = sorted(trades, key=lambda r: date_key(r.get("sell_date") or r.get("datetime", "")))
    if len(ordered_trades) >= 2:
        trade_mid = len(ordered_trades) // 2
        trade_parts = [ordered_trades[:trade_mid], ordered_trades[trade_mid:]]
        trade_ok = []
        for part in trade_parts:
            pnls = [parse_float(r.get("pnl")) or 0.0 for r in part]
            trade_ok.append(sum(pnls) > 0)
    else:
        trade_ok = [False, False]

    return "True" if all(event_ok) and all(trade_ok) else "False"


def build_single_stock_applicability(
    events: List[Dict[str, str]],
    trades: List[Dict[str, str]],
    outcome_index: Dict[Tuple[str, int], Dict[str, str]],
) -> List[Dict[str, object]]:
    buy_events = [row for row in events if is_buy_countdown_complete(row)]
    completed = completed_trades(trades)

    events_by_stock: Dict[str, List[Dict[str, str]]] = {}
    trades_by_stock: Dict[str, List[Dict[str, str]]] = {}
    for row in buy_events:
        events_by_stock.setdefault(row.get("security", ""), []).append(row)
    for row in completed:
        trades_by_stock.setdefault(row.get("security", ""), []).append(row)

    raw_rows: List[Dict[str, object]] = []
    securities = sorted(set(events_by_stock.keys()) | set(trades_by_stock.keys()))
    for security in iter_progress(securities, desc="Building single-stock applicability", total=len(securities)):
        stock_events = events_by_stock.get(security, [])
        stock_trades = trades_by_stock.get(security, [])
        returns: List[float] = []
        mfes: List[float] = []
        maes: List[float] = []
        for event in stock_events:
            ret, mfe, mae = directional_metrics(event, outcome_index, 20)
            if ret is not None:
                returns.append(ret)
            if mfe is not None:
                mfes.append(mfe)
            if mae is not None:
                maes.append(mae)
        pnls = [parse_float(t.get("pnl")) or 0.0 for t in stock_trades]
        pl_ratio = profit_loss_ratio_from_pnls(pnls)
        win_rate = trade_win_rate_from_pnls(pnls)
        row = {
            "security": security,
            "event_count": len(stock_events),
            "completed_trade_count": len(stock_trades),
            "ret_20d_median": quantile(returns, 0.5),
            "mfe_20d_median": quantile(mfes, 0.5),
            "mae_20d_median": quantile(maes, 0.5),
            "trade_win_rate": win_rate,
            "avg_profit_loss_ratio": pl_ratio,
            "max_drawdown": max_drawdown_from_pnls(pnls),
            "execution_rate": safe_div(float(len(stock_trades)), float(len(stock_events))) if stock_events else None,
            "split_consistent": split_consistency(stock_events, stock_trades, outcome_index),
        }
        raw_rows.append(row)

    eligible = [
        row for row in raw_rows
        if int(row["event_count"]) >= SINGLE_STOCK_EVENT_MIN_COUNT
        and int(row["completed_trade_count"]) >= SINGLE_STOCK_TRADE_MIN_COUNT
    ]
    market_ret = quantile([float(r["ret_20d_median"]) for r in eligible if r["ret_20d_median"] is not None], 0.5)
    market_mae = quantile([float(r["mae_20d_median"]) for r in eligible if r["mae_20d_median"] is not None], 0.5)
    market_win = quantile([float(r["trade_win_rate"]) for r in eligible if r["trade_win_rate"] is not None], 0.5)
    market_pl = quantile([
        float(r["avg_profit_loss_ratio"]) for r in eligible
        if r["avg_profit_loss_ratio"] is not None and not math.isinf(float(r["avg_profit_loss_ratio"]))
    ], 0.5)

    output: List[Dict[str, object]] = []
    for row in raw_rows:
        enough_sample = (
            int(row["event_count"]) >= SINGLE_STOCK_EVENT_MIN_COUNT
            and int(row["completed_trade_count"]) >= SINGLE_STOCK_TRADE_MIN_COUNT
        )
        ret_ok = market_ret is not None and row["ret_20d_median"] is not None and float(row["ret_20d_median"]) > market_ret
        mae_ok = market_mae is not None and row["mae_20d_median"] is not None and float(row["mae_20d_median"]) > market_mae
        win_ok = market_win is not None and row["trade_win_rate"] is not None and float(row["trade_win_rate"]) > market_win
        pl_value = row["avg_profit_loss_ratio"]
        pl_ok = market_pl is not None and pl_value is not None and (math.isinf(float(pl_value)) or float(pl_value) > market_pl)
        selected = enough_sample and ret_ok and mae_ok and win_ok and pl_ok and row["split_consistent"] == "True"
        reason_parts = []
        if not enough_sample:
            reason_parts.append("insufficient sample")
        if enough_sample and not ret_ok:
            reason_parts.append("event return not above market median")
        if enough_sample and not mae_ok:
            reason_parts.append("adverse move not better than market median")
        if enough_sample and not (win_ok and pl_ok):
            reason_parts.append("trade quality not above market median")
        if enough_sample and row["split_consistent"] != "True":
            reason_parts.append("subperiod consistency failed")
        output.append({
            "security": row["security"],
            "event_count": row["event_count"],
            "completed_trade_count": row["completed_trade_count"],
            "ret_20d_median": fmt(row["ret_20d_median"]),
            "mfe_20d_median": fmt(row["mfe_20d_median"]),
            "mae_20d_median": fmt(row["mae_20d_median"]),
            "trade_win_rate": fmt(row["trade_win_rate"]),
            "avg_profit_loss_ratio": fmt(row["avg_profit_loss_ratio"]),
            "max_drawdown": fmt(row["max_drawdown"]),
            "execution_rate": fmt(row["execution_rate"]),
            "split_consistent": row["split_consistent"],
            "selected": "True" if selected else "False",
            "applicability_note": "candidate" if selected else "; ".join(reason_parts),
        })

    output.sort(
        key=lambda r: (
            r["selected"] != "True",
            -(parse_float(r.get("ret_20d_median")) or -999.0),
            -(parse_float(r.get("trade_win_rate")) or -999.0),
        )
    )
    return output


# =============================================================================
# Stratified Analysis
# =============================================================================

def liquidity_bucket(row: Dict[str, str]) -> str:
    amount = parse_float(row.get("pre20_avg_amount"))
    if amount is None:
        return "Unknown"
    if amount >= 300_000_000:
        return "High Liquidity"
    if amount <= 50_000_000:
        return "Low Liquidity"
    return "Mid Liquidity"


def volatility_bucket(row: Dict[str, str]) -> str:
    vol = parse_float(row.get("pre20_volatility"))
    if vol is None:
        return "Unknown"
    if vol >= 0.035:
        return "High Volatility"
    if vol <= 0.015:
        return "Low Volatility"
    return "Mid Volatility"


def market_bucket(row: Dict[str, str]) -> str:
    ret = parse_float(row.get("pre20_return"))
    if ret is None:
        return "Unknown"
    if ret > 0.05:
        return "Uptrend"
    if ret < -0.05:
        return "Downtrend"
    return "Sideways"


def quality_bucket(row: Dict[str, str]) -> str:
    setup = parse_bool(row.get("setup_perfect") or row.get("setup_is_perfect"))
    countdown = parse_bool(row.get("perfect") or row.get("countdown_is_perfect"))
    if setup and countdown:
        return "Perfect Setup + Countdown"
    if setup:
        return "Perfect Setup"
    if countdown:
        return "Perfect Countdown"
    return "Non-perfect"


def build_stratified_summary(events: List[Dict[str, str]], trades: List[Dict[str, str]]) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    dimensions = [
        ("Market State", market_bucket),
        ("Liquidity", liquidity_bucket),
        ("Volatility", volatility_bucket),
        ("Signal Quality", quality_bucket),
    ]
    trade_by_setup_dt: Dict[Tuple[str, str], List[Dict[str, str]]] = {}
    for trade in completed_trades(trades):
        trade_by_setup_dt.setdefault((trade.get("security", ""), trade.get("setup_completed_at", "")), []).append(trade)

    for dimension, bucket_func in dimensions:
        grouped_events: Dict[str, List[Dict[str, str]]] = {}
        grouped_trades: Dict[str, List[Dict[str, str]]] = {}
        for event in events:
            bucket = bucket_func(event)
            grouped_events.setdefault(bucket, []).append(event)
            related = trade_by_setup_dt.get((event.get("security", ""), event.get("setup_last_dt", "")), [])
            if related:
                grouped_trades.setdefault(bucket, []).extend(related)
        for bucket in sorted(grouped_events.keys()):
            sample_trades = grouped_trades.get(bucket, [])
            pnls = [parse_float(r.get("pnl")) or 0.0 for r in sample_trades]
            wins = [p for p in pnls if p > 0]
            rows.append({
                "dimension": dimension,
                "bucket": bucket,
                "event_count": len(grouped_events[bucket]),
                "trade_count": len(sample_trades),
                "trade_win_rate": fmt(safe_div(float(len(wins)), float(len(sample_trades))) if sample_trades else None),
                "trade_total_pnl": fmt(sum(pnls), 2),
                "trade_max_drawdown": fmt(max_drawdown_from_pnls(pnls)),
            })
    return rows


# =============================================================================
# Charts
# =============================================================================

def get_plot_modules():
    try:
        import matplotlib
        matplotlib.use("Agg", force=True)
        import matplotlib.pyplot as plt
        from matplotlib.ticker import PercentFormatter
        return plt, PercentFormatter
    except Exception:
        return None, None


def save_trade_chart(rows: List[Dict[str, object]], output_dir: Path) -> None:
    plt, PercentFormatter = get_plot_modules()
    if plt is None:
        print("Skipped charts: matplotlib is unavailable.")
        return
    labels = [str(r["scenario"]) for r in rows]
    win_rates = [parse_float(r.get("win_rate")) or 0.0 for r in rows]
    returns = [parse_float(r.get("total_return")) or 0.0 for r in rows]
    fig, ax = plt.subplots(figsize=(12, 6))
    x = list(range(len(labels)))
    ax.plot(x, win_rates, marker="o", label="Win Rate")
    ax.plot(x, returns, marker="o", label="Total Return")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_title("Trade Performance by Signal Quality")
    ax.set_ylabel("Rate")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend(loc="best")
    fig.tight_layout()
    path = output_dir / "trade_performance_by_quality.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    print("Saved: {}".format(path))


def save_single_stock_chart(rows: List[Dict[str, object]], output_dir: Path) -> None:
    plt, PercentFormatter = get_plot_modules()
    if plt is None:
        return
    candidates = [r for r in rows if r.get("selected") == "True"]
    sample = candidates if candidates else rows[:20]
    if not sample:
        return
    labels = [str(r["security"]) for r in sample]
    ret20 = [parse_float(r.get("ret_20d_median")) or 0.0 for r in sample]
    win_rates = [parse_float(r.get("trade_win_rate")) or 0.0 for r in sample]
    fig, ax = plt.subplots(figsize=(max(12, len(labels) * 0.5), 6))
    x = list(range(len(labels)))
    ax.plot(x, ret20, marker="o", label="20D Directional Return Median")
    ax.plot(x, win_rates, marker="o", label="Trade Win Rate")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_title("Single-stock Applicability Candidates" if candidates else "Top Single-stock Applicability Sample")
    ax.set_ylabel("Rate")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.legend(loc="best")
    fig.tight_layout()
    path = output_dir / "single_stock_applicability.png"
    fig.savefig(path, dpi=180)
    plt.close(fig)
    print("Saved: {}".format(path))


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    args = parse_args()
    run_dir = resolve_path(args.run_folder)
    output_dir = run_dir / OUTPUT_FOLDER_NAME
    if not run_dir.exists() or not run_dir.is_dir():
        raise FileNotFoundError("Run folder not found: {}".format(run_dir))

    events = read_csv(run_dir / "td_events.csv")
    outcomes = read_csv(run_dir / "event_outcomes.csv")
    trades = read_csv(run_dir / "trade.csv")
    outcome_index = build_outcome_index(outcomes)

    event_rows = build_event_study(events, outcome_index)
    event_header = ["event_group", "event_count"]
    for window in EVENT_WINDOWS:
        event_header.extend([
            "ret_{}d_count".format(window), "ret_{}d_mean".format(window), "ret_{}d_median".format(window),
            "ret_{}d_q25".format(window), "ret_{}d_q75".format(window), "ret_{}d_win_rate".format(window),
            "mfe_{}d_median".format(window), "mae_{}d_median".format(window),
        ])
    write_csv(output_dir / "event_study_summary.csv", event_rows, event_header)

    trade_rows = summarize_trades(list(iter_progress(trades, desc="Summarizing trades", total=len(trades))))
    trade_header = [
        "scenario", "trade_count", "win_rate", "avg_profit_loss_ratio",
        "total_pnl", "total_return", "max_drawdown", "sharpe",
    ]
    write_csv(output_dir / "trade_performance_summary.csv", trade_rows, trade_header)
    save_trade_chart(trade_rows, output_dir)

    strat_rows = build_stratified_summary(events, trades)
    strat_header = [
        "dimension", "bucket", "event_count", "trade_count",
        "trade_win_rate", "trade_total_pnl", "trade_max_drawdown",
    ]
    write_csv(output_dir / "stratified_summary.csv", strat_rows, strat_header)

    stock_rows = build_single_stock_applicability(events, trades, outcome_index)
    stock_header = [
        "security", "event_count", "completed_trade_count",
        "ret_20d_median", "mfe_20d_median", "mae_20d_median",
        "trade_win_rate", "avg_profit_loss_ratio", "max_drawdown",
        "execution_rate", "split_consistent", "selected", "applicability_note",
    ]
    write_csv(output_dir / "single_stock_applicability.csv", stock_rows, stock_header)
    save_single_stock_chart(stock_rows, output_dir)

    print("Done. Events={}, trades={}.".format(len(events), len(trades)))


if __name__ == "__main__":
    main()
